spring:
  application:
    name: summary

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring.data.mongodb.uri: mongodb+srv://user:user@cluster0.f2x3m.mongodb.net/test?retryWrites=true&w=majority
sprint.data.mongodb.database: summary
