spring:
  application:
    name: auth
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.f2x3m.mongodb.net/test?retryWrites=true&w=majority

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
