#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://user:user@cluster0.f2x3m.mongodb.net/test?retryWrites=true&w=majority
#
#  endpointUrl: https://s3.cloudLocation.amazonaws.com
#  accessKey: AKIA2IDELYFWGDLSOBEH
#  secretKey: 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
#  bucketName: teamproj2bucket
#  region: us-east-2
spring:
  application:
    name: timesheet
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.f2x3m.mongodb.net/test?retryWrites=true&w=majority

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#spring.data.mongodb.uri= mongodb+srv://user:user@cluster0.f2x3m.mongodb.net/test?retryWrites=true&w=majority
endpointUrl: https://s3.cloudLocation.amazonaws.com
accessKey: AKIA2IDELYFWGDLSOBEH
secretKey: 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
bucketName: teamproj2bucket
region: us-east-2